### ISSUE TITLE
 error: instagramMedia.data is not iterable

### ISSUE THREAD

**Issue by sgandolfo** [webvibe-io/strapi-plugin-instagram#10]
After setting up everything in Strapi according to the instruction in the documentation, I get the following error:

```
error: instagramMedia.data is not iterable
TypeError: instagramMedia.data is not iterable
    at Object.downloadImages (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@webvibe-io/strapi-plugin-instagram/server/services/instagramBasicApi.js:68:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getImages (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@webvibe-io/strapi-plugin-instagram/server/controllers/instagramBasicApi.js:24:18)
    at async returnBodyMiddleware (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
    at async /Users/stefanogandolfo/Documents/Projects/panevinoCMS/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
```

I am using ngrok to have a public domain while developing/testing my application. Whenever I click the 'Download Images' button in the Configuration screen for Instagram in Strapi, I get a 500 Internal Server Error from ngrok on the POST /instagram/downloadImages endpoint.

Have I misconfigured something or is this a bug?

**Comment by sgandolfo** [comment]
Fixed the issue by upgrading axios to latest version (1.2.3)
