### ISSUE TITLE
Emoji causes `ER_TRUNCATED_WRONG_VALUE_FOR_FIELD`

### ISSUE THREAD

**Issue by SvenWesterlaken** [webvibe-io/strapi-plugin-instagram#18]
```bash
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x90\x99' for column 'caption' at row 1
    at Sequence._packetToError (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at TLSSocket.ondata (node:internal/streams/readable:766:22)
    at TLSSocket.emit (node:events:512:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/sven/code/joliedesign/strapi/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/sven/code/joliedesign/strapi/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/sven/code/joliedesign/strapi/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/sven/code/joliedesign/strapi/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/sven/code/joliedesign/strapi/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/Users/sven/code/joliedesign/strapi/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/Users/sven/code/joliedesign/strapi/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/sven/code/joliedesign/strapi/node_modules/knex/lib/execution/runner.js:300:20)
```

I ran into this error when my caption had an emoji (🐙). Just here leaving a note in case someone else has the same issue. I solved it by making sure the database encoding was set to `utf8mb4` (which it was) & setting the charset of the connection (which was not set and therefore created the error). Adding the following line in `/config/database.ts` did the trick:

```js
charset: env('DATABASE_CHARSET', 'utf8mb4'),
```

**Comment by SvenWesterlaken** [comment]
I added a quick note to the documentation addressing this issue.

**Comment by kepes** [comment]
merged
