### ISSUE TITLE
Strapi Broken after Install Plugin

### ISSUE THREAD

**Issue by Marvv90** [webvibe-io/strapi-plugin-instagram#24]
Hi, 

Versions:
strapi@4.9.1
node@16.13.0
npm@9.6.2

Reproduce:
Fresh Strapi install, install Plugin.

Error:
`ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/react-fontawesome' in '/Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/Settings'
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:805:13
    at eval (eval at create (/Users/name/Desktop/Projekte/testing-stapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/Users/name/Desktop/Projekte/testing-stapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:436:22
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:677:25
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:881:8
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:1001:5
resolve '@fortawesome/react-fontawesome' in '/Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/Settings'
  Parsed request is a module
  using description file: /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/package.json (relative path: ./admin/src/pages/Settings)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/Settings/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/node_modules doesn't exist or is not a directory
      looking for modules in /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules
        single file module
          using description file: /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/package.json (relative path: ./node_modules/@fortawesome/react-fontawesome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.tsx doesn't exist
        /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome doesn't exist
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/name/Desktop/Projekte/testing-stapi/node_modules
        single file module
          using description file: /Users/name/Desktop/Projekte/testing-stapi/package.json (relative path: ./node_modules/@fortawesome/react-fontawesome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.tsx doesn't exist
        /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome doesn't exist
      /Users/name/Desktop/Projekte/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/node_modules doesn't exist or is not a directory
      /Users/name/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/package.json (relative path: ./node_modules/@fortawesome/react-fontawesome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.tsx doesn't exist
        /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/react-fontawesome' in '/Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/Settings'
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:805:13
    at eval (eval at create (/Users/name/Desktop/Projekte/testing-stapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/Users/name/Desktop/Projekte/testing-stapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:436:22
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:677:25
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:881:8
    at /Users/name/Desktop/Projekte/testing-stapi/node_modules/webpack/lib/NormalModuleFactory.js:1001:5
resolve '@fortawesome/react-fontawesome' in '/Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/Settings'
  Parsed request is a module
  using description file: /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/package.json (relative path: ./admin/src/pages/Settings)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/Settings/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/pages/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/src/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/admin/node_modules doesn't exist or is not a directory
      looking for modules in /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules
        single file module
          using description file: /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/package.json (relative path: ./node_modules/@fortawesome/react-fontawesome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome.tsx doesn't exist
        /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/strapi-plugin-instagram/node_modules/@fortawesome/react-fontawesome doesn't exist
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/@webvibe-io/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/Projekte/testing-stapi/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/name/Desktop/Projekte/testing-stapi/node_modules
        single file module
          using description file: /Users/name/Desktop/Projekte/testing-stapi/package.json (relative path: ./node_modules/@fortawesome/react-fontawesome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome.tsx doesn't exist
        /Users/name/Desktop/Projekte/testing-stapi/node_modules/@fortawesome/react-fontawesome doesn't exist
      /Users/name/Desktop/Projekte/node_modules doesn't exist or is not a directory
      /Users/name/Desktop/node_modules doesn't exist or is not a directory
      /Users/name/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/package.json (relative path: ./node_modules/@fortawesome/react-fontawesome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome.tsx doesn't exist
        /Users/name/Desktop/Projekte/testing-stapi/node_modules/@strapi/admin/node_modules/@fortawesome/react-fontawesome doesn't exist
error Command failed with exit code 1.`

**Comment by Marvv90** [comment]
Need to install `npm i @fortawesome/react-fontawesome`
